// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messaging.proto

package si.ita.services.orders.messaging;

public interface CreateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
