// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messaging.proto

package si.ita.services.orders.messaging;

public interface CreateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string queue = 1;</code>
   * @return The queue.
   */
  java.lang.String getQueue();
  /**
   * <code>string queue = 1;</code>
   * @return The bytes for queue.
   */
  com.google.protobuf.ByteString
      getQueueBytes();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
