// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messaging.proto

package si.ita.services.orders.messaging;

public final class MessagingProto {
  private MessagingProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017messaging.proto\"/\n\rCreateRequest\022\r\n\005qu" +
      "eue\030\001 \001(\t\022\017\n\007message\030\002 \001(\t\"!\n\016CreateResp" +
      "onse\022\017\n\007message\030\001 \001(\t2\202\001\n\tMessaging\0227\n\022S" +
      "endMessageToQueue\022\016.CreateRequest\032\017.Crea" +
      "teResponse\"\000\022<\n\025ReadMessagesFromQueue\022\016." +
      "CreateRequest\032\017.CreateResponse\"\0000\001B4\n si" +
      ".ita.services.orders.messagingB\016Messagin" +
      "gProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CreateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CreateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateRequest_descriptor,
        new java.lang.String[] { "Queue", "Message", });
    internal_static_CreateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CreateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
